### ISSUE TITLE
Modelisation de la nouvelle coque pour les robots deltas

### ISSUE THREAD

**Issue by wonwon0** [RoboCupULaval/Tasks#17]

**Comment by wonwon0** [comment]
elle doit avoir EN DESSOUS de 180 mm de diametre et le robot ne doit pas ere plus haut que 150 mm de hauteur en INCLUANT le pattern de couleur qu'on met pour spotter les robots avec la camera

**Comment by TwistedSim** [comment]
Est-ce que cette tâche est terminé? je crois qu'on est rendu à la production des coques ?
