### ISSUE TITLE
Faire un inventaire du matériel de vision de Robocup

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/Tasks#69]
Il faudrait vérifier qu'il nous manque rien lorsque l'on redonne le matériel à la compétition. Sa serait vraiment plate si un terrain manque une caméra par exemple.

**Comment by TwistedSim** [comment]
https://docs.google.com/spreadsheets/d/12J_bN-xZXMU_9SvCZiwDxQ3co2F6wuy_ZmhKK-Hlmnk/edit?usp=sharing
